language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install pylint
  - pip install flake8
  - pip install codecov
  - pip3 install https://download.pytorch.org/whl/cpu/torch-1.1.0-cp36-cp36m-linux_x86_64.whl
  - pip3 install https://download.pytorch.org/whl/cpu/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl

# command to run tests
script:
  - python -m pytest
  - python -m pytest --cov=track tests/
  - flake8 track
  - pylint track; true
  - codecov
