language: python

python:
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install pylint
  - pip install flake8
  - pip install codecov
  - pip install mypy
  - pip install https://download.pytorch.org/whl/cpu/torch-1.1.0-cp36-cp36m-linux_x86_64.whl
  - pip install https://download.pytorch.org/whl/cpu/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl

jobs:
  include:
    - stage: unit-test
      script:
        - travis_wait python -m pytest --cov=track tests/
        - codecov
    - stage: pep8
      script:
        - flake8 track
    - stage: pylint
      script:
        - pylint track; true
    - stage: typecheck
      script:
        - mypy track; true
