language: python

python:
  - "3.6"

install:
  - pip install -e .
  - pip install pytest
  - pip install pytest-cov
  - pip install flake8
  - pip install codecov
  - pip install psycopg2-binary
  - pip install https://download.pytorch.org/whl/cpu/torch-1.1.0-cp36-cp36m-linux_x86_64.whl
  - pip install https://download.pytorch.org/whl/cpu/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl
  - pip install git+https://github.com/Delaunay/orion.git@track
  - ./install_cockroachdb.sh
  - export PATH="$PATH:."

jobs:
  include:
    - stage: unit-test
      script:
        - python -m pytest --cov=track tests/unit
        - python -m pytest --cov-append --cov=track tests/e2e
        - codecov
    - stage: pep8
      script:
        - flake8 track
