language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install pylint
  - pip install flake8
  - pip install codecov

# command to run tests
script:
  - python -m pytest
  - python -m pytest --cov=track tests/
  - flake8 track
  - pylint track; true
  - codecov
